### ISSUE TITLE
Bouncy blocks do not drop themselves

### ISSUE THREAD

**Issue by hibiii** [deli73/bouncy-castle#2]
Hi, thanks for making the mod!

The blocks, despite having loot tables, do not actually drop when either mined (with or without silk touch) or exploded.

This is caused because the JSON files for the blocks are in `bouncycastle:loot_tables`, rather than `bouncycastle:loot_tables/blocks`.

**Comment by deli73** [comment]
oops! thanks for letting us know

**Comment by deli73** [comment]
should be fixed in 1.0.3 [https://github.com/deli73/bouncy-castle/commit/e19e0dc641db56d1e6683abb7d9284a0d217083a](url)
